### ISSUE TITLE
First Example in README does not work.

### ISSUE THREAD

**Issue by MadBomber** [OlympiaAI/raix#2]
/Users/dewayne/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/raix-0.3.2/lib/raix/chat_completion.rb:154:in `openrouter_request': undefined method `complete' for nil (NoMethodError)

        Raix.configuration.openrouter_client.complete(messages, model:, extras: params.compact, stream:)
                                            ^^^^^^^^^
	from /Users/dewayne/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/raix-0.3.2/lib/raix/chat_completion.rb:74:in `chat_completion'

**Comment by markhallen** [comment]
@MadBomber 

There is some config missing from the docs. I'll raise a PR later if the repo allows me, but here is the minimum I added to get this `complete` working in a new rails app.

`config/initializers/raix.rb`

```ruby
Raix.configuration.openrouter_client = OpenRouter::Client.new
```

`config/initializers/open_router.rb`

```ruby
OpenRouter.configure do |config|
  config.access_token = ENV.fetch("OPEN_ROUTER_ACCESS_TOKEN")
end
```
