### ISSUE TITLE
Missing dependency? cannot load such file -- raix/message_adapters/base (LoadError)

### ISSUE THREAD

**Issue by aquabu** [OlympiaAI/raix#4]
In a non-rails script calling `bundle exec ruby script.rb` on a `script.rb` file containing just `require 'raix'` throws the error:
`cannot load such file -- raix/message_adapters/base (LoadError)`

From the README, it appears this shouldn't be a sufficient set of libraries to run without `activesupport`. However the simple script call is failing on `require 'raix'` and `require 'activesupport'` doesn't affect the error thrown.

**Comment by obie** [comment]
Investigating now, thanks for reporting.

**Comment by obie** [comment]
Should be resolved in 0.4.1... apologies for the inconvenience.

**Comment by aquabu** [comment]
Awesome. Thanks. The error has been resolved for me by upgrading to `0.4.1`. I did need to add `gem "openai"` to my `Gemfile` but that was something I could resolve at the project level.
